flask_app/routes/author.py
from sqlite3 import Cursor
from flask import render_template, Blueprint, g, current_app
import json

author_bp = Blueprint("author", __name__)

@author_bp.route('/author/<pid>/')
def author(pid):
    kwargs: dict[str, dict] = {}
    cursor: Cursor = g.db.cursor()
    logger = current_app.logger

    person_data: tuple = cursor.execute(
        """SELECT person_id, person_name, person_dept, 
        CASE WHEN person_correct_scholar = 1 THEN person_scholar ELSE NULL END AS person_scholar, 
        person_orcid, 
        CASE WHEN person_correct_scholar = 1 THEN person_scholar_citedby ELSE NULL END AS person_scholar_citedby
        FROM persons WHERE person_id = ?""",
        (int(pid),)
    ).fetchone()

    if not person_data:
        return render_template("404.html.j2", wats={"type":"Author", "id":pid}), 404

    kwargs["person_data"] = dict(
        zip(
            ("pers_id", "pers_name", "dept" , "sch_id", "orc_id", "sch_cited"),
            person_data
        )
    )
    # links for orcid and scholar profiles

    # TODO: display timetable, preferably filterable
    # --> last two years
    # --> link to filterable table
    kwargs["summary"] = {}
    kwargs["summary"]["rows"] = list(map(lambda x: x[1:12], cursor.execute("SELECT * FROM Windowed_data WHERE person_id = ?", (int(pid),)).fetchall()))
    kwargs["summary"]["columns"] = [
        ["number", "Window"], ["number", "Average contribution to publications"], ["number", "Crossref citation count"],
        ["number", "Altmetric citation count"], ["number", "Google Scholar citation count"], ["number", "Number of publications participating on"],
        ["number", "Number of students teached"], ["number", "Weighted average subject rating"], ["number", "Credit-students"],
        ["number", "Number of unique courses teached"], ["number", "Number of hours teached"]
    ]
    kwargs["summary"]["name"] = "Sum_table"

    kwargs["timetables"] = {}
    kwargs["timetables"]["rows"] = cursor.execute(
        """ SELECT tbl_year, tbl_semester, tbl_code, tbl_subject, tbl_groups
        FROM timetables
        WHERE tbl_person_id = ? AND tbl_year >= 2020 ORDER BY tbl_year, tbl_semester DESC;""",
        (int(pid), )
    ).fetchall()
    kwargs["timetables"]["columns"] = [
        ["number", "Year"], ["string", "Semester"], ["string", "Subject code"], 
        ["string", "Subject name"], ["string", "Study groups"]
    ]
    kwargs["timetables"]["name"] = "Rozvrh"

    kwargs["publications"] = {}
    kwargs["publications"]["rows"] = cursor.execute(
        """SELECT publ_title, publ_year, publ_epc_new, COALESCE(sch_citations, ""), COALESCE(sch_id, ""), COALESCE(publ_doi, "")
        FROM publications 
        JOIN authorships ON publ_id = auth_publ_id
        JOIN scholar_data ON publ_id = sch_publ_id
        WHERE auth_person_id = ? AND publ_year > 2021
""", (pid, )).fetchall()
    kwargs["publications"]["columns"] = [
        ["string", "Title"], ["number", "Year"], ["string", "EPC category"], ["number", "Google Scholar citations"],
        ["string", "Google Scholar publication ID"], ["string", "DOI"]
    ]
    kwargs["publications"]["name"] = "pub_tab"
    print(kwargs["publications"])


    return render_template("author.html.j2", **kwargs)

flask_app/routes/general.py
from math import ceil
from flask import request, render_template, g, Blueprint, redirect, flash
from flask_login import LoginManager, login_user, logout_user, login_required
from plotly.utils import PlotlyJSONEncoder
import plotly.express as px
import json
from .utils import _dea_model_reader, _list_of_dea_models, User, map_data_labels
import pandas as pd
import numpy as np


general_bp = Blueprint("general", __name__)

@general_bp.route('/search')
@login_required
def search():
    query = request.args.get('query', "").lower()
    where = request.args.get("where", "")
    method = request.args.get("method", "")
    page = int(request.args.get("page", 1))
    cursor = g.db.cursor()
    per_page = 50
    print(f"{repr(query)}")

    # Filter data based on the search query
    if method == "begins":
        search_query = query + "%"
    elif method == "contains":
        search_query = "%"+query+"%"
    else:
        raise NotImplementedError

    if where == "authors":
        results = cursor.execute(
            """SELECT person_name, person_id, person_dept 
            FROM persons 
            WHERE person_name_norm LIKE ? AND person_dept NOT NULL
            ORDER BY person_name""",
            (search_query,)
        ).fetchall()
        heading = "Search results"
    elif where == "publications":
        print("test")
        results = cursor.execute(
            """SELECT publ_title, publ_id, publ_year 
            FROM publications 
            WHERE publ_title LIKE ? 
            ORDER BY publ_title""",
            (search_query,)
        ).fetchall()
        heading = "Search results"
    else:
        return render_template('404.html.j2')
    return render_template(
        'search.html.j2',
        wats=results[(page-1)*per_page:page*per_page],
        heading=heading,
        page=page, max_pages=ceil((len(results)/per_page)),
        where=where, query=query, method=method
    )

@general_bp.route('/')
@general_bp.route('/index')
def home():
    # TODO add summary, some stats on all data, ...
    dea_toc = _list_of_dea_models()
    return render_template('index.html.j2', dea_toc=dea_toc)

@general_bp.route('/login', methods=['GET', 'POST'])
def login():
    # If a post request was made, find the user by 
    # filtering for the username
    if request.method == "POST":
        data = g.db.cursor().execute("""SELECT * FROM "App_user_list" WHERE username = ?""", (request.form.get("username"),)).fetchone()
        user = User(*data) if data else None
        # Check if the password entered is the 
        # same as the user's password
        if user and user.password == request.form.get("password"):
            # Use the login_user method to log in the user
            login_user(user)
            flash('Logged in successfully.')
            if (next_page := request.args.get("next")):
                return redirect(next_page)
            return redirect("/index")
        # Redirect the user back to the home
        # (we'll create the home route in a moment)
    return render_template("login.html.j2")

@general_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash('Logged out successfully.')
    return redirect("/index")

@general_bp.route('/dea')
@login_required
def dea():
    path = request.args.get('path', "")
    x = request.args.get('x', "credit_student")
    y = request.args.get('y', "scholar")
    x_scale = request.args.get("x_scale", False) == "True"
    y_scale = request.args.get("y_scale", False) == "True"
    person_id = request.args.get("person_id")

    dea_data = pd.read_csv(open(f"model_data/{path}.csv", "rt", encoding="utf-8"))
    dea_data["eff"] = np.round(dea_data["eff"], 2)
    dea_data["window"] = dea_data["window"].apply(lambda x: f"{2023 - 3*x - 2}-{2023 - 3*x}")
    dea_data["Title"] = dea_data["pay_grade"].apply(lambda x: {1.0:"Assistant professor", 1.2:"Associate professor", 1.4:"Full professor"}[x])
    dea_data["size"] = dea_data["eff"]
    dea_data.loc[dea_data["eff"]<10,"size"] = 11 - dea_data.loc[dea_data["eff"]<10, "eff"]
    dea_data.loc[dea_data["eff"]>=10, "size"] = 1
    dea_data["size"] = dea_data["size"]
    dea_data.loc[dea_data["size"].isna(), "size"] = 1

    figure = px.scatter(
        dea_data,
        x=x, y=y,
        color="Title",
        log_x=x_scale, log_y=y_scale,
        symbol="Title",
        hover_data={"eff":True, "person_id":True, "window":True, "Title":True, "pay_grade":False},
        custom_data=np.stack((dea_data["person_id"], dea_data["window"], dea_data["Title"], dea_data["eff"]), axis=0),
        size=dea_data["size"].to_list(),
        opacity=0.8,
        render_mode="svg",
        labels={
            x:map_data_labels.get(x, x),
            y:map_data_labels.get(y, y)
        },
    )
    figure.update_coloraxes(showscale=False)
    figure.update_traces(hovertemplate="<br>".join([
        "Person id: %{customdata[0]}",
        "Time window: %{customdata[1]}",
        "Title: %{customdata[2]}",
        "x: %{x}",
        "y: %{y}",
        "Efficiency: %{customdata[3]}",
    ]))
    figure_json = json.dumps(figure, cls=PlotlyJSONEncoder)

    dea_data["dept"] = dea_data.loc[:,[a.startswith("K") for a in dea_data.columns]].idxmax(axis=1)
    figure2 = px.box(
        dea_data,
        x="dept",
        y="eff",
        color="dept",
        notched=True,
        labels={
            "dept":"Department",
            "eff":"Efficiency",
        },
    )
    figure2.update_layout(yaxis_range=[0,10])
    figure2_json = json.dumps(figure2, cls=PlotlyJSONEncoder)

    descriptors = list(_list_of_dea_models("dict")[path].values()) + [x, y, path, str(x_scale), str(y_scale)]
    return render_template("dea.html.j2", wats=["g1", "vg1", figure_json], wats2=["g2", "vg2", figure2_json], descriptors=descriptors)


@general_bp.route('/px')
def express_test():
    df = px.data.medals_wide()
    fig1 = px.bar(x=np.arange(10_000)/100, y=np.sin(np.arange(10_000)/100), title="Wide-Form Input")
    graph1JSON = json.dumps(fig1, cls=PlotlyJSONEncoder)
    wats = ["g1", "vg1", graph1JSON]
    return render_template('plotlyexpress.html.j2', wats = wats)

flask_app/routes/publications.py
from sqlite3 import Cursor
from flask import render_template, Blueprint, g, current_app, abort
from plotly.utils import PlotlyJSONEncoder
import plotly.express as px
import json
import pandas as pd


publication_bp = Blueprint("publication", __name__)

@publication_bp.route('/publication/<publ_index>/')
def publication(publ_index):
    cursor = g.db.cursor()
    wats={}
    wats["pub"] = cursor.execute(
        """ SELECT * FROM publications JOIN scholar_data ON publ_id = sch_publ_id WHERE publ_id = ?
        """, (publ_index,)).fetchone()
    a = cursor.execute("""SELECT a.*, p.person_name
FROM authorships AS a JOIN persons AS p ON auth_person_id = person_id WHERE auth_publ_id = ?""", (publ_index, )).fetchall()
    frame = pd.DataFrame(a, columns=["auth_index", "person_id", "publ_id", "Contribution", "Status", "Name"])
    if frame["Contribution"].sum()<100:
        frame.loc[-1] = [None, None, publ_index, 100 - frame["Contribution"].sum(), None, "Non-faculty member(s)"]
    wats["authors"] = frame.to_numpy().tolist()
    plot = px.pie(frame, "Name", "Contribution", title="Contribution of individual authors to the publication")
    wats["pie"] = ["p", "vp", json.dumps(plot, cls=PlotlyJSONEncoder)]

    return render_template("publication.html.j2", wats=wats)

flask_app/templates/404.html.j2
{% extends "layout.html.j2" %}
{% block title %} 
{% if wats %}
{{wats["type"]}} not found 
{% else %}
404 - Page not found
{% endif %}
{% endblock title %}
{% block content %}
{% if wats %}
    {{wats["type"]}} # {{wats["id"]}} not found.
{% else %}
404 - Page not found
{% endif %}
{% endblock content %}

flask_app/templates/author.html.j2
{% extends "layout.html.j2" %}
{% block title %}{{ person_data["pers_name"] }} | Autor{% endblock title %}
{% block scripts %}
    {% include "charts/loader.html.j2" %}
    {% with columns=summary["columns"], rows=summary["rows"], name=summary["name"] %}
        {% include "charts/table_script.html.j2" %}
    {% endwith %}
    {% with columns=timetables["columns"], rows=timetables["rows"], name=timetables["name"] %}
        {% include "charts/table_script.html.j2" %}
    {% endwith %}
    {% with columns=publications["columns"], rows=publications["rows"], name=publications["name"] %}
        {% include "charts/table_script.html.j2" %}
    {% endwith %}
{% endblock %}

{% block content %}
    <p>
        <b>{{ person_data["pers_name"] }}</b>, {{ person_data["dept"]}}
    </p>
    {% if person_data["sch_id"] is not none %}
        <a href="https://scholar.google.com/citations?hl=en&user={{ person_data['sch_id'] }}" target="_blank">Google scholar profile</a>
    {% endif %}
    {% if person_data["orc_id"] is not none %}
        <a href="https://orcid.org/{{ person_data['orc_id'] }}" target="_blank">Orcid profile</a>
    {% endif %}
    <br>
    List of summary of the data we have stored. Range of years the window represents is [2023 - 2 - 3*window, 2023 - 3*window]
    {% with name=summary["name"], width=none, height=none %}
        {% include "charts/div.html.j2" %}
    {% endwith %}
    List of lectures from last three years:
    {% with name=timetables["name"], width=none, height=none %}
        {% include "charts/div.html.j2" %}
    {% endwith %}
    List of publications from last three years:
    {% with name=publications["name"], width=none, height=none %}
        {% include "charts/div.html.j2" %}
    {% endwith %}
{% endblock %}

flask_app/templates/author_on.html.j2
<!doctype html>
<html>

    <head>
        <title>Index</title>
    </head>

    <style>
        table {
            border-collapse: collapse;
        }

        table,
        td,
        th {
            border: 1px solid;
        }
    </style>

    <body>
        {% if not wats:%}
            <p>No record</p>
        {% else %}
            <table>
                {% for wat in wats: %}
                    <tr>
                        <td>
                            <a href="{{ url_for("author", pid=wat[1]) }}">{{wat[0]}}</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% endif %}
    </body>

</html>

flask_app/templates/dash_template.html
{% extends "layout.html.j2" %}
{% block content %}
{%app_entry%}
<footer>
    {%config%}
    {%scripts%}
    {%renderer%}
</footer>
{% endblock content %}

flask_app/templates/dea.html.j2
{% extends "layout.html.j2" %}
{% block title %}
{{ descriptors[0] }} - DEA model
{% endblock title %}
{% block scripts %}
    {% include "charts/px_script.html.j2" %}
{% endblock scripts %}
{% block content %}
    <form method="GET" action="{{ url_for('general.dea') }}">
        <input type="hidden" id="path" name="path" value="{{ descriptors[6] }}""> 
        <label for="x">Plot on x-axis:</label>
        <select name="x" id="x" required>
            <optgroup label="Inputs">
            {% for optgroup in descriptors[1] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[4]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
            <optgroup label="Outputs">
            {% for optgroup in descriptors[2] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[4]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
            <optgroup label="Results">
            {% for optgroup in descriptors[3] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[4]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
        </select><br>
        <label for="y">Plot on y-axis:</label>
        <select name="y" id="y" required>
            <optgroup label="Inputs">
            {% for optgroup in descriptors[1] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[5]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
            <optgroup label="Outputs">
            {% for optgroup in descriptors[2] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[5]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
            <optgroup label="Results">
            {% for optgroup in descriptors[3] %}
                <option value={{optgroup[0]}} {% if optgroup[0]|string() == descriptors[5]|string() %} selected {% endif %}>{{optgroup[1]}}</option>
            {% endfor %}
            </optgroup>
        </select><br>
        <label for="x_scale"> Use log scale on x-axis</label>
        <input type="checkbox" id="x_scale" name="x_scale" value="True" {% if "True"|string() == descriptors[7]|string() %} checked {% endif%}><br>
        <label for="y_scale"> Use log scale on y-axis</label>
        <input type="checkbox" id="y_scale" name="y_scale" value="True" {% if "True"|string() == descriptors[8]|string() %} checked {% endif%}><br>
        <input type="submit" value="Submit">
    </form>
    <form method="GET" action="{{ url_for('general.dea') }}">
        <input type="hidden" id="path" name="path" value="{{ descriptors[6] }}""> 
        <input type="hidden" id="x" name="x" value="{{ descriptors[5] }}""> 
        <input type="hidden" id="y" name="y" value="{{ descriptors[4] }}""> 
        <input type="hidden" id="x_scale" name="x_scale" value="{{ descriptors[8] }}""> 
        <input type="hidden" id="y_scale" name="y_scale" value="{{ descriptors[7] }}""> 
        <button name="submit" value="submit" type="submit">Flip axis</button>
    </form>
    {% with name=wats[0], var_name=wats[1], JSONdata=wats[2]%}
        {% include "charts/div_px.html.j2" %}
    {% endwith %}
    {% with name=wats2[0], var_name=wats2[1], JSONdata=wats2[2]%}
        {% include "charts/div_px.html.j2" %}
    {% endwith %}


{% endblock content %}

flask_app/templates/index.html.j2
{% extends "layout.html.j2" %}
{% block scripts %}
<style>
    th, td {
        padding: 15px;
    }
</style>
{% endblock %}
{% block content %}
<h1>Search</h1>
<form method="GET" action="{{ url_for('general.search') }}">
    <table>
        <tr>
            <td>
                Search by:<br>
                <input type="radio" name="where" id="Autor" value="authors" required checked><label for="Autor">Author name</label><br>
                <input type="radio" name="where" id="Nazov" value="publications"><label for="Nazov">Publication title</label>
            </td>
            <td>
                How:<br>
                <input type="radio" name="method" id="Zacina" value="begins" required checked><label for="Zacina">Begins with</label><br>
                <input type="radio" name="method" id="Obsahuje" value="contains" ><label for="Obsahuje">Includes</label>
            </td>
        </tr>
        <tr >
            <td colspan=2 style="text-align: center;">
                <input type="text" name="query" placeholder="Enter your search" required>
                <button type="submit">Search</button>
            </td>
        </tr>
        <tr>
            <td><a href="{{ url_for('general.search', query="", where='authors', method='begins')}}">List of all authors</a></td>
            <td><a href="{{ url_for('general.search', query="", where='publications', method='begins')}}">List of all publications</a></td>
        </tr>
    </table>
</form>

<h1>List of DEA models</h1>
<table>
    <tr>
        <th>Name</th>
        <th>Inputs</th>
        <th>Outputs</th>
    </tr>
    {% for row in dea_toc %}
    <tr>
        <td><a href="{{ url_for('general.dea', path=row[0], x_scale='True', y_scale='True')}}">{{row[1]}}</a></td>
        <td>
            <ul>
                {% for a in row[2] %}
                    <li>{{a}}</li>
                {% endfor %}
            </ul>
        </td>
        <td>
            <ul>
                {% for a in row[3] %}
                    <li>{{a}}</li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    {% endfor %}
</table>
</ul>

<!-- 
<table>
    <tr>
        <th>Osoby abecedne</th>
        <th>Publikácie abecedne</th>
    </tr>
    {% for wat in wats %}
        <tr>
            <td>
                <a
                    href="\{\{ url_for("author_on", letter=wat) }}">\{\{ wat }}</a>
            </td>
            <td>
                <a
                    href="\{\{ url_for("publication_on", letter=wat) }}">\{\{ wat }}</a>
            </td>
        </tr>
    {% endfor %}
</table>
-->
{% endblock %}

flask_app/templates/layout.html.j2
<!doctype html>
<html>

    <head>
        <title>{% block title %}Index{% endblock %}</title>
        {% block scripts %}{% endblock %}
        <style>#footer {bottom: 0; height: 2.5rem;}</style>
    </head>

    <style>
        table {
            border-collapse: collapse;
        }

        table,
        td,
        th {
            border: 1px solid;
        }
    </style>

    <body>
        <nav>
            <a href="\">Index</a> | 
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('general.logout')}}">logout</a>
            {% else %}
                <a href="{{ url_for('general.login')}}">login</a>
            {% endif %}
        </nav>
        <br>
        <div id="content">
            {% block content %} Something's wrong, you should't see this message {% endblock %}
        </div>
    </body>

    <footer id="footer">František. Created 2024</footer>
</html>

flask_app/templates/login.html.j2
{% extends "layout.html.j2" %}
{% block content %}
    <h1>Login to your account</h1>
    <form action="#" method="post">
        <label for="username">Username:</label>
        <input type="text" name="username" />
        <label for="password">Password:</label>
        <input type="password" name="password" />
        <button type="submit">Submit</button>
    </form>
{% endblock content %}

flask_app/templates/plotlyexpress.html.j2
{% extends "layout.html.j2" %}
{% block scripts %}
    {% include "charts/px_script.html.j2" %}
{% endblock scripts %}
{% block content %}
    {% with name=wats[0], var_name=wats[1], JSONdata=wats[2]%}
        {% include "charts/div_px.html.j2" %}
    {% endwith %}
{% endblock content %}

flask_app/templates/publication.html.j2
{% extends "layout.html.j2" %}
{% block title %}{{ wats["pub"][1] }} | Autor{% endblock title %}
{% block scripts %}
    {% include "charts/px_script.html.j2" %}
{% endblock scripts %}
{% block content %}
    <h1>{{wats["pub"][1]}}</h1>
    Authors:
        {% for author in wats["authors"] %}
            {% if author[-1]|string != "Non-faculty member(s)" %}
                {# <a href="{{ url_for("general.search", page=1, where=where, method=method, query=query) }}">1 &lt;&lt;</a> #}
                <a href="{{ url_for('author.author', pid=author[1]) }}">{{author[-1]}}</a>, 
            {% else %}
                {{author[-1]}}
            {% endif %}
        {% endfor %}<br>
    EPC category: {{ wats["pub"][9]}}<br>
    {% if wats["pub"][12] %}
        Citations on Google Scholar: {{wats["pub"][12]}}
    {% endif %}<br>
    {% with name=wats["pie"][0], var_name=wats["pie"][1], JSONdata=wats["pie"][2]%}
        {% include "charts/div_px.html.j2" %}
    {% endwith %}
{% endblock content %}

flask_app/templates/publication_on.html.j2
<!doctype html>
<html>

    <head>
        <title>Index</title>
    </head>

    <style>
        table {
            border-collapse: collapse;
        }

        table,
        td,
        th {
            border: 1px solid;
        }
    </style>

    <body>
        {% if not wats:%}
        <p>Žiaden záznam</p>
        {% else %}
        <table>
        {% for wat in wats %}
            <tr>
                <td>
                    <a href="{{ url_for("publication", publ_index=wat[1]) }}">{{wat[0]}}</a>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </body>

</html>

flask_app/templates/search.html.j2
{% extends "layout.html.j2" %}
{% block content %}
    {% if not wats:%}
        <p>No record</p>
    {% else %}
    <div>
        {% if page > 1 %}
            <a href="{{ url_for("general.search", page=1, where=where, method=method, query=query) }}">1 &lt;&lt;</a> | 
            <a href="{{ url_for("general.search", page=page-1, where=where, method=method, query=query) }}">&lt;</a> |
        {% endif %}
        {{ page }}
        {% if page < max_pages %}
            | 
            <a href="{{ url_for("general.search", page=page+1, where=where, method=method, query=query) }}">&gt;</a> | 
            <a href="{{ url_for("general.search", page=max_pages, where=where, method=method, query=query) }}">&gt;&gt; {{max_pages}}</a>
        {% endif %}
        <br><br>
        <table>
            <th>{{heading}}</th> <!-- add colspan -->
            {% for wat in wats: %}
                <tr>
                    <td>
                    {% if where=="authors" %}
                        <a href="{{ url_for("author.author", pid=wat[1]) }}">{{wat[0]}} | {{wat[2]}}</a>
                    {% elif where=="publications" %}
                        <a href="{{ url_for("publication.publication", publ_index=wat[1]) }}">{{wat[0]}} | {{wat[2]}}</a>
                    {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br>

        {% if page > 1 %}
            <a href="{{ url_for("general.search", page=1, where=where, method=method, query=query) }}">1 &lt;&lt;</a> | 
            <a href="{{ url_for("general.search", page=page-1, where=where, method=method, query=query) }}">&lt;</a> |
        {% endif %}
        {{ page }}
        {% if page < max_pages %}
            | 
            <a href="{{ url_for("general.search", page=page+1, where=where, method=method, query=query) }}">&gt;</a> | 
            <a href="{{ url_for("general.search", page=max_pages, where=where, method=method, query=query) }}">&gt;&gt; {{max_pages}}</a>
        {% endif %}
    </div>
    {% endif %}
{% endblock %}

flask_app/templates/vis.html.j2
<!doctype html>
<html>

    <head>
        <title>{% block title %}Index{% endblock %}</title>
        {% include "charts/px_script.html.j2" %}
    </head>

    <body>
        <div id="content">
            {% with name=wats[0], var_name=wats[1], JSONdata=wats[2]%}
                {% include "charts/div_px.html.j2" %}
            {% endwith %}
        </div>
    </body>
</html>